# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[5.37601722e-01 6.91118810e-02 5.95025421e-01 ... 8.94112136e-01
  8.00809312e-01 5.50815269e-04]
 [4.09622823e-01 4.45366852e-01 9.62785106e-01 ... 1.88210436e-01
  4.95353610e-01 2.37014586e-01]
 [5.89096391e-01 9.72581357e-01 8.28432380e-02 ... 1.43700208e-01
  3.14006157e-01 4.59302134e-01]
 ...
 [4.92134330e-02 1.15104664e-01 4.17918226e-01 ... 2.62686311e-01
  1.98877615e-01 8.70072506e-01]
 [8.08245196e-01 1.79664331e-01 6.96472491e-01 ... 6.19452244e-01
  4.53913121e-01 6.04565467e-01]
 [7.61894840e-01 6.62636812e-02 3.16325145e-01 ... 4.14770916e-01
  5.40604969e-01 2.55700547e-01]]
[[0.48073249 0.33870263 0.26699287 ... 0.67083224 0.23533499 0.79515902]
 [0.0671345  0.77935976 0.03290821 ... 0.26572015 0.69484797 0.60553306]
 [0.01950739 0.85126421 0.28229814 ... 0.49130492 0.16259063 0.61122237]
 ...
 [0.48585792 0.89098224 0.94941978 ... 0.18164751 0.9834278  0.11548701]
 [0.35074334 0.8203

Без использования numpy

In [ ]:
def mult(a, b):
	c = []
	for i in range(0, len(a)):
		temp = []
		for j in range(0, len(b[0])):
			s = 0
			for k in range(0, len(a[0])):
				s += a[i][k] * b[k][j]
			temp.append(s)
		c.append(temp)

	return c

C использованием numpy

In [ ]:
def np_mult(a, b):
	return np.matmul(a, b)


In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 631 ms, sys: 276 µs, total: 631 ms
Wall time: 642 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 866 µs, sys: 107 µs, total: 973 µs
Wall time: 5.38 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.67265862 0.58667727 0.75814227] [0.93660239 0.07926096 0.84717053]


In [ ]:
def scalar_product(v1, v2):
  return sum(x*y for x, y in zip(v1, v2))

In [ ]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 26 µs, sys: 3 µs, total: 29 µs
Wall time: 31.9 µs
CPU times: user 649 µs, sys: 20 µs, total: 669 µs
Wall time: 533 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

In [ ]:
Методы numpy работают быстрее за счет того, что коллекции в numpy хранят значение одного типа и занимают меньше места в памяти. Numpy примерно в 5-100 раз быстрее, чем обычное вычисление.

**Ответ:** ________________________________

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diagonal(a)
  return diag[diag % 2 == 0].sum()


In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 7, 8, 2, 8],
       [7, 7, 5, 5, 3],
       [8, 9, 9, 1, 7],
       [6, 4, 7, 3, 8],
       [3, 9, 8, 8, 4]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 197 µs, sys: 26 µs, total: 223 µs
Wall time: 232 µs


12

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    result = np.zeros_like(A)
    for i in range(len(A)):
        result[i, :] = np.cumsum(A[i])
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[7.37983104e-01 2.41012789e-01 4.72998401e-01 4.52099591e-02
 9.56718472e-01 9.23692302e-01 8.92947242e-02 3.21023393e-02
 6.76704882e-02 2.37384032e-01 4.76761632e-01 9.93014904e-01
 7.84819755e-01 7.50299237e-01 1.48250874e-01 2.71312922e-01
 7.50083296e-01 2.99199639e-02 9.07441646e-02 4.45305021e-01
 3.65386166e-01 4.62189518e-01 3.71312271e-02 2.79465023e-01
 3.77923857e-01 9.72597238e-01 7.20042451e-01 5.85227714e-01
 3.58558522e-01 3.62808999e-01 2.55084017e-01 8.49009630e-01
 6.33349542e-01 5.75636403e-01 7.74904159e-01 4.13945567e-01
 7.24372875e-01 3.38421368e-01 4.59180110e-01 5.79299143e-01
 5.41650290e-01 4.01086253e-01 7.68674385e-01 2.67422427e-01
 1.80546581e-01 2.99386826e-01 6.01099505e-01 1.06870712e-01
 6.21789026e-01 2.69958565e-02 2.90569133e-01 7.23267605e-01
 6.61276525e-01 8.62232487e-01 1.03337323e-01 3.18191422e-01
 5.67090184e-01 2.36431031e-02 2.73492774e-02 1.44497051e-01
 7.30848910e-01 7.26696117e-01 2.31729139e-01 4.24735362e-01
 3.76478194e-01 5.682541

IndexError: ignored

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    ia = np.asarray(a)
    n = len(ia)
    if n == 0:
        return (None, None)
    else:
        y = np.array(ia[1:] != ia[:-1])
        i = np.append(np.where(y), n - 1)
        z = np.diff(np.append(-1, i))
        return(ia[i], z)

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 978 µs, sys: 0 ns, total: 978 µs
Wall time: 902 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
import copy

def transform(X, a=1):
    """
    param X: np.array
    """
    result = []

    if len(X.shape) == 1:
        X = np.expand_dims(X, axis=0)

    for idx, arr in enumerate(X):
        Y = copy.deepcopy(arr)
        Y[1::2] = a
        Y[::2] = arr[::2]**3
        Y = Y[::-1]
        result.append(np.hstack((arr,Y)))

    return result

In [1]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

NameError: ignored